### ISSUE TITLE
how to use something similar  without CPLEX on windows ?

### ISSUE THREAD

**Issue by Sandy4321** [ustunb/risk-slim#4]
how to use something similar  without CPLEX on windows ?

**Comment by ustunb** [comment]
Sorry for the late reply! I'm closing this issue since there's no easy to have this running without CPLEX right now (on any platform). I'm hoping to have a version that uses an open source solver next year.

**Comment by Sandy4321** [comment]
I'm hoping to have a version that uses an open source solver next year.
pls do it asap

**Comment by shrikanth95** [comment]
Hello Dr Ustun

I have access to CPLEX but I am having an issue installing the library on windows. The error message is as follows:

`LINK : fatal error LNK1181: cannot open input file 'm.lib'
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.24.28314\\bin\\HostX86\\x64\\link.exe' failed with exit status 1181
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\shrikanth\appdata\local\programs\python\python37\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'D:\\Work\\NC State\\RiskSlim\\risk-slim\\setup.py'"'"'; __file__='"'"'D:\\Work\\NC State\\RiskSlim\\risk-slim\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.`


Is this a known windows issue? I tried installing several VS tools but I still wasn't able to complete the installation.

**Comment by ustunb** [comment]
Hello. I'm not sure since I don't use Windows, but I would recommend posting the problem on the CPLEX forums. Here is the link: https://www.ibm.com/developerworks/community/forums/html/forum?id=11111111-0000-0000-0000-000000002059

**Comment by jmcrafty** [comment]
> 
> 
> Hello Dr Ustun
> 
> I have access to CPLEX but I am having an issue installing the library on windows. The error message is as follows:
> 
> `LINK : fatal error LNK1181: cannot open input file 'm.lib' error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.24.28314\\bin\\HostX86\\x64\\link.exe' failed with exit status 1181 ---------------------------------------- ERROR: Command errored out with exit status 1: 'c:\users\shrikanth\appdata\local\programs\python\python37\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'D:\\Work\\NC State\\RiskSlim\\risk-slim\\setup.py'"'"'; __file__='"'"'D:\\Work\\NC State\\RiskSlim\\risk-slim\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.`
> 
> Is this a known windows issue? I tried installing several VS tools but I still wasn't able to complete the installation.

Hi, I was having this same issue. I was able to fix it (as far as I can tell) by removing the lines 48 and 55 in setup.py. So the extensions function now looks like this:
```
#fast log loss
extensions =[
    Extension(
        DISTNAME + ".loss_functions." + "fast_log_loss",
        [DISTNAME + "/loss_functions/fast_log_loss.pyx"],
        include_dirs=[numpy.get_include(), scipy.get_include()],
        extra_compile_args=["-ffast-math"]
    ),
    Extension(
        DISTNAME + ".loss_functions." + "lookup_log_loss",
        [DISTNAME + "/loss_functions/lookup_log_loss.pyx"],
        include_dirs=[numpy.get_include(), scipy.get_include()],
        extra_compile_args=["-ffast-math"])
]
```
This was on Windows 10, Python 3.7.5, and Visual Studio 14.23
Hope this helps others in the future!
