### ISSUE TITLE
open-source solver

### ISSUE THREAD

**Issue by alexlaurence** [ustunb/risk-slim#7]
Any updates on the open source solver development? Been two years... Perhaps this is abandonware now?

**Comment by ustunb** [comment]
Sorry! 

The open-source solver will, unfortunately, have to wait until Fall 2020 at the very least. 

The project is not "abandonware," but I only have time to handle bugs and make easy changes at the moment.

I am hoping to implement major functionality later this year, or potentially this summer if I can recruit new contributors.
