### ISSUE TITLE
Trying to understand output

### ISSUE THREAD

**Issue by DaveDeCaprio** [ustunb/risk-slim#8]
I'm trying to understand the output I am getting from risk_slim.
In the results dictionary there is a key called solution which has an array that is the same length as my input data set.  

What's confusing me is that shouldn't my solution have 1 fewer column than my inputs, given that the first column of the inputs is label I am trying to train on?

**Comment by ustunb** [comment]
The first column should be the coefficient for the intercept. This is just
a column of ones. If you didn't include a column of ones in your original
dataset, then it should be added automatically. Does this make sense?


On Sun, Mar 22, 2020 at 9:53 PM David DeCaprio <notifications@github.com>
wrote:

> I'm trying to understand the output I am getting from risk_slim.
> In the results dictionary there is a key called solution which has an
> array that is the same length as my input data set.
>
> What's confusing me is that shouldn't my solution have 1 fewer column than
> my inputs, given that the first column of the inputs is label I am trying
> to train on?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ustunb_risk-2Dslim_issues_8&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=eB_oRo404IL7R_uIoh5wjffvGNzbFPBTaB7jG1xZ3Ck&m=xNc83CeCRXkzVGJTrgl0xXx6_IjTuHFL_FboTcHP7QY&s=lAvsRlxHgS0s5xSxQhTCVVxnZWc9arLt1FGs7h-nYpM&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ABM4UCNWXHS4EWJT77FSRCLRI26HZANCNFSM4LRQZK4A&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=eB_oRo404IL7R_uIoh5wjffvGNzbFPBTaB7jG1xZ3Ck&m=xNc83CeCRXkzVGJTrgl0xXx6_IjTuHFL_FboTcHP7QY&s=j_nikZV3q7PYWpyVN4bAtNGAgNj15LrqsO52zN8oWNQ&e=>
> .
>


-- 
Berk Ustun
Postdoctoral Fellow, Center for Research on Computation for Society,
Harvard SEAS
https://www.berkustun.com <http://www.berkustun.com>

**Comment by DaveDeCaprio** [comment]
Yes, I thought that might be what's happening.  Good to know.  Thanks.
